# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        # with => use for provide parameters to this action
        with:
          go-version: "1.20"
        # id => use for unique identifier for refer this step from other
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

        # don't have to build because the application will be built automatically when we run go test
      # - name: Build
      #   run: go build -v ./...

      - name: Test
        run: make test
